name: Check commit format
description: Checks a pull request commit against Homebrew style
author: jonchang
branding:
  icon: git-commit
  color: green
inputs:
  token:
    description: GitHub token
    required: false
    default: ${{github.token}}
  failure_label:
    description: Label to set on failure. Default is automerge-skip
    required: false
    default: automerge-skip
runs:
  using: node16
  main: main.js
