name: Setup Gems Cache
description: Setup Gems Caching for workflow
inputs:
  gems-path:
    description: Homebrew's Ruby gems path
    required: true
  gems-hash:
    description: Homebrew's Ruby Gemfile.lock sha256sum
    required: true
outputs:
  outcome:
    description: Brew Install Bundler Gems steps outcome
    value: ${{ steps.gems.outcome }}

runs:
  using: composite
  steps:
    - name: Cache Homebrew Gems
      id: cache
      uses: actions/cache@v3
      with:
        path: ${{ inputs.gems-path }}
        key: ${{ runner.os }}-rubygems-${{ inputs.gems-hash }}
        restore-keys: ${{ runner.os }}-rubygems-

    - name: Install Homebrew Gems
      id: gems
      run: brew install-bundler-gems
      if: steps.cache.outputs.cache-hit != 'true'
      shell: bash
