name: Find related workflow run ID
description: Finds the run ID of a workflow run given another run ID on the same commit
inputs:
  run-id:
    description: Workflow run ID
    required: true
  workflow-name:
    description: Name of workflow to look up
    required: true
  repository:
    description: Repository containing the workflow run
    required: false
    default: ${{ github.repository }}
  token:
    description: Authentication token for `gh`
    required: false
    default: ${{ github.token }}
outputs:
  workflow-run-id:
    description: >
      ID of the related workflow run.
      Also available as `env.workflow_run_id`.
runs:
  using: node20
  main: main.mjs
************* Crash Head ****************
Time Of Crash      : 2025_02_20-02_03_02
Rom Info           : RomInfo{name=samsung, version=up1a.231005.007.a736bxxsaeyb2}
Device Manufacturer: samsung
Device Model       : SM-A736B
Android Version    : 14
Android SDK        : 34
App VersionName    : 2.5.8
App VersionCode    : 152
************* Crash Head ****************