name: Cache Homebrew Prefix
description: Cache Homebrew prefix and install formulae.
inputs:
  install:
    description: Formula names passed to `brew install --formula`.
    required: false
    default: ""
  brewfile:
    description: Install formulae from `./Brewfile` instead of `install`.
    required: false
    default: "false"
  uninstall:
    description: Automatically uninstall existing formulae before installing.
    required: false
    default: "false"
outputs:
  prefix:
    description: Homebrew prefix path.
    value: ${{ steps.prefix.outputs.path }}
  cache-key:
    description: Cache key derived from formula list.
    value: ${{ steps.cache-key.outputs.key }}
runs:
  using: composite
  steps:
    - name: Handle existing Homebrew formulae
      run: |
        installed_formulae="$(brew list --formula 2>/dev/null || true)"
        if [[ -z "${installed_formulae}" ]]; then
          exit 0
        fi

        if [[ "${UNINSTALL}" != "true" ]]; then
          echo "::error::Homebrew already has formulae installed. Set with.uninstall=true to remove them automatically." >&2
          echo "${installed_formulae}" >&2
          exit 1
        fi

        brew test-bot --only-cleanup-before

        remaining_formulae="$(brew list --formula 2>/dev/null || true)"
        if [[ -n "${remaining_formulae}" ]]; then
          echo "::error::brew test-bot cleanup did not remove all formulae." >&2
          echo "${remaining_formulae}" >&2
          exit 1
        fi
      shell: /bin/bash -euo pipefail {0}
      env:
        UNINSTALL: ${{ inputs.uninstall }}

    - name: Resolve Homebrew prefix
      id: prefix
      run: echo "path=$(brew --prefix)" >> "${GITHUB_OUTPUT}"
      shell: /bin/bash -euo pipefail {0}

    - name: Compute cache key prefix
      id: cache-prefix
      run: |
        cache_key_prefix="${RUNNER_OS}"
        arch="$(uname -m)"
        if [[ "${RUNNER_OS}" = "macOS" ]]; then
          macos_full_version="$(sw_vers -productVersion)"
          macos_version="${macos_full_version%%.*}"
          cache_key_prefix="macos-${macos_version}-${arch}"
        elif [[ "${RUNNER_OS}" = "Linux" ]]; then
          if [[ -r /etc/os-release ]]; then
            . /etc/os-release
            os_id="${ID:-linux}"
            os_version="${VERSION_ID:-unknown}"
          else
            os_id="linux"
            os_version="unknown"
          fi
          cache_key_prefix="${os_id}-${os_version}-${arch}"
        else
          cache_key_prefix="${RUNNER_OS}-${arch}"
        fi
        echo "prefix=${cache_key_prefix}" >> "${GITHUB_OUTPUT}"
      shell: /bin/bash -euo pipefail {0}

    - name: Save Homebrew repository git HEAD
      id: save-git-head
      run: |
        brew_repo="$(brew --repository)"
        if [[ -d "${brew_repo}/.git" ]]; then
          echo "sha=$(git -C "${brew_repo}" rev-parse HEAD)" >> "${GITHUB_OUTPUT}"
          echo "repo=${brew_repo}" >> "${GITHUB_OUTPUT}"
        fi
      shell: /bin/bash -euo pipefail {0}

    - name: Restore Homebrew prefix cache
      id: cache-restore
      uses: actions/cache/restore@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
      with:
        path: ${{ steps.prefix.outputs.path }}
        key: homebrew-prefix-${{ steps.cache-prefix.outputs.prefix }}-restore
        restore-keys: |
          homebrew-prefix-${{ steps.cache-prefix.outputs.prefix }}-

    - name: Restore Homebrew repository git state
      if: steps.save-git-head.outputs.sha != ''
      run: |
        current_sha="$(git -C "${BREW_REPO}" rev-parse HEAD 2>/dev/null || true)"
        if [[ "${current_sha}" != "${SAVED_SHA}" ]]; then
          git -C "${BREW_REPO}" fetch origin "${SAVED_SHA}"
          git -C "${BREW_REPO}" checkout --force "${SAVED_SHA}"
        fi
      shell: /bin/bash -euo pipefail {0}
      env:
        BREW_REPO: ${{ steps.save-git-head.outputs.repo }}
        SAVED_SHA: ${{ steps.save-git-head.outputs.sha }}

    - name: Install Homebrew formulae
      run: |
        if [[ "${BREWFILE}" = "true" ]]; then
          if [[ -n "${INSTALL//[[:space:]]/}" ]]; then
            echo "Cannot use both brewfile=true and install input." >&2
            exit 1
          fi
          if [[ ! -f Brewfile ]]; then
            echo "Brewfile not found in current directory." >&2
            exit 1
          fi
          brew bundle --file Brewfile --no-upgrade
          exit 0
        else
          raw_args="${INSTALL}"
        fi

        args=()
        for token in ${raw_args}; do
          if [[ "${token}" = -* ]]; then
            echo "Options are not allowed in install list: ${token}" >&2
            exit 1
          fi
          if [[ ! "${token}" =~ ^[A-Za-z0-9._/@-]+$ ]]; then
            echo "Invalid package name: ${token}" >&2
            exit 1
          fi
          args+=("${token}")
        done
        if [[ "${#args[@]}" -eq 0 ]]; then
          echo "No packages provided to brew install." >&2
          exit 1
        fi
        brew install --formula "${args[@]}"
      shell: /bin/bash -euo pipefail {0}
      env:
        INSTALL: ${{ inputs.install }}
        BREWFILE: ${{ inputs.brewfile }}

    - name: Compute Homebrew cache key
      id: cache-key
      run: |
        brew list --formula --versions | sort > "${RUNNER_TEMP}/brew-list.txt"

        if command -v shasum >/dev/null 2>&1; then
          hash_cmd=(shasum -a 256)
        else
          hash_cmd=(sha256sum)
        fi
        key="$("${hash_cmd[@]}" "${RUNNER_TEMP}/brew-list.txt" | awk '{print $1}')"
        echo "key=${key}" >> "${GITHUB_OUTPUT}"
      shell: /bin/bash -euo pipefail {0}

    - name: Save Homebrew prefix cache
      uses: actions/cache/save@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
      with:
        path: ${{ steps.prefix.outputs.path }}
        key: homebrew-prefix-${{ steps.cache-prefix.outputs.prefix }}-${{ steps.cache-key.outputs.key }}
