name: Populate Bundler Gems Cache
description: Populates the Homebrew Bundler RubyGems Cache
runs:
  using: "composite"
  steps:
    - name: Set up Homebrew
      id: set-up-homebrew
      uses: Homebrew/actions/setup-homebrew@master

    - name: Set up RubyGems cache
      shell: bash
      run: |
        cache_key_prefix="$RUNNER_OS"
        if [[ "$RUNNER_OS" = macOS ]]
        then
          macos_full_version="$(sw_vers -productVersion)"
          macos_version="${macos_full_version%%.*}"
          arch="$(uname -m)"
          cache_key_prefix="${macos_version}-${arch}"
        fi
        echo "cache_key_prefix=${cache_key_prefix}" >> "$GITHUB_ENV"

    - name: Cache Homebrew Bundler RubyGems
      id: cache
      uses: actions/cache@v3
      with:
        path: ${{ steps.set-up-homebrew.outputs.gems-path }}
        key: ${{ env.cache_key_prefix }}-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
        restore-keys: ${{ env.cache_key_prefix }}-rubygems-

    - name: Install Homebrew Bundler RubyGems
      if: steps.cache.outputs.cache-hit != 'true'
      shell: bash
      run: brew install-bundler-gems
