name: Git try push
description: Try to push to remote repository specified number of times
author: dawidd6
branding:
  icon: arrow-up-circle
  color: blue
inputs:
  token:
    description: GitHub token (used for push)
    required: false
  directory:
    description: Repository directory
    required: false
  remote:
    description: Git remote
    required: false
    default: origin
  branch:
    description: Git branch
    required: false
    default: master
  tries:
    description: How many times to try pushing
    required: false
    default: "20"
  force:
    description: Whether to force-with-lease push (rebasing on origin_branch if needed)
    required: false
  origin_branch:
    description: Branch to rebase on, defaults to branch
    required: false
runs:
  using: node16
  main: main.js
