name: Setup Homebrew
description: Set up Homebrew environment
author: dawidd6
branding:
  icon: settings
  color: yellow
inputs:
  test-bot:
    description: Install the `homebrew/test-bot` tap.
    required: false
    default: true
  debug:
    description: Show debugging output
    required: false
    default: false
outputs:
  gems-path:
    description: Homebrew's Ruby gems path
    value: ${{steps.setup.outputs.gems-path}}
  gems-hash:
    description: Homebrew's Ruby Gemfile.lock sha256sum
    value: ${{steps.setup.outputs.gems-hash}}
runs:
  using: composite
  steps:
    - run: |
        "$GITHUB_ACTION_PATH/main.sh" '${{ inputs.test-bot }}' '${{ inputs.debug }}'
      shell: bash
      id: setup
