name: Brew script

on:
  pull_request:
    paths:
      - '**brew-script**'
      - 'package.json'
      - 'package-lock.json'
      - 'node_modules/**'

jobs:
  script:
    runs-on: ubuntu-latest
    env:
      HOMEBREW_FILENAME: ".revision"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure PATH
        run: echo "/home/linuxbrew/.linuxbrew/bin" >> "${GITHUB_PATH}"

      - name: Update brew
        run: brew update-reset "$(brew --repo)"

      - name: Script
        uses: ./brew-script/
        with:
          script: |
            ohai 'test'
            revision = Utils.safe_popen_read("git", "rev-parse", "HEAD")
            file = ENV["HOMEBREW_FILENAME"]
            File.write(file, revision)
            $stderr.puts "test"

      - name: Test
        run: test "$GITHUB_SHA" = "$(cat "$HOMEBREW_FILENAME")"
