name: Bump formulae

on:
  pull_request:
    paths:
      - "**bump-formulae**"
      - "package.json"
      - "package-lock.json"
      - "node_modules/**"

jobs:
  bump:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update core
        run: brew update-reset "$(brew --repo Homebrew/core)"

      - name: Bump
        uses: ./bump-formulae/
        with:
          token: ${{github.token}}
          formulae: hello
