name: Count bottles

on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - "**count-bottles**"
      - "package.json"
      - "package-lock.json"
      - "node_modules/**"

jobs:
  syntax:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check scripts
        run: shellcheck --enable=all count-bottles/*.sh
