name: Download artifact (download)

on:
  pull_request:
    paths:
      - '**download-artifact**'
      - 'package.json'
      - 'package-lock.json'
      - 'node_modules/**'

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Wait
        run: sleep 60s

      - name: Download
        uses: ./download-artifact/
        with:
          workflow: download-artifact-upload.yml
          name: artifact
          path: artifact
          commit: ${{github.event.pull_request.head.sha}}

      - name: Test
        run: grep "$GITHUB_SHA" artifact/sha
