name: Download artifact (download)

on:
  workflow_run:
    workflows:
      - Download artifact (upload)
    types: 
      - completed

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download
        uses: ./download-artifact/
        with:
          workflow: download-artifact-upload.yml
          name: artifact
          path: artifact
      - name: Test
        run: cat artifact/sha | grep $GITHUB_SHA
