name: Post pull request review

on:
  pull_request:
    paths:
      - '**post-review**'
      - 'package.json'
      - 'package-lock.json'
      - 'node_modules/**'

jobs:
  post-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Test
        uses: ./post-review/
        with:
          token: ${{github.token}}
          pull_request: ${{github.event.pull_request.number}}
          event: COMMENT
          body: This is a comment.
