name: Node test

on:
  push:
    branches:
      - main
      - master
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-slim
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: '24'

      - name: Run type checking
        run: npm install && npx tsc

      - name: Run tests
        run: npm test -- --experimental-test-coverage --test-reporter lcov --test-reporter-destination lcov.info

      - name: Upload coverage results
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          files: lcov.info
          disable_search: true
          token: ${{ secrets.CODECOV_TOKEN }}
